const actionTypes = Object.freeze({
    FETCH_USER_LOGIN_SUCCES: 'FETCH_USER_LOGIN_SUCCES',


    // admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAILDED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSOTION_FAILDED: 'FETCH_POSOTION_FAILDED',

    FETCH_ROLEID_SUCCESS: 'FETCH_ROLEID_SUCCESS',
    FETCH_ROLEID_FAILDED: 'FETCH_ROLEID_FAILDED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAILDED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILDED: 'DELETE_USER_FAILDED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAILDED',





})

export default actionTypes;