const actionTypes = Object.freeze({
    FETCH_USER_LOGIN_SUCCES: 'FETCH_USER_LOGIN_SUCCES',


    // admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIDED: 'FETCH_GENDER_FAIDED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSOTION_FAIDED: 'FETCH_POSOTION_FAIDED',

    FETCH_ROLEID_SUCCESS: 'FETCH_ROLEID_SUCCESS',
    FETCH_ROLEID_FAIDED: 'FETCH_ROLEID_FAIDED',


})

export default actionTypes;